name 'puppetlabs-stdlib'
version '2.5.1'

author 'puppetlabs'
license 'Apache 2.0'
project_page 'https://github.com/puppetlabs/puppetlabs-stdlib'
source 'git://github.com/puppetlabs/puppetlabs-stdlib'
summary 'Puppet Module Standard Library'
description 'Standard Library for Puppet Modules'
